// megafunction wizard: %ALTIOBUF%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altiobuf_out 

// ============================================================
// File Name: Driver128b.v
// Megafunction Name(s):
// 			altiobuf_out
//
// Simulation Library Files(s):
// 			cycloneiii
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 13.1.0 Build 162 10/23/2013 SJ Web Edition
// ************************************************************


//Copyright (C) 1991-2013 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altiobuf_out CBX_AUTO_BLACKBOX="ALL" DEVICE_FAMILY="Cyclone III" ENABLE_BUS_HOLD="FALSE" LEFT_SHIFT_SERIES_TERMINATION_CONTROL="FALSE" NUMBER_OF_CHANNELS=128 OPEN_DRAIN_OUTPUT="FALSE" PSEUDO_DIFFERENTIAL_MODE="FALSE" USE_DIFFERENTIAL_MODE="FALSE" USE_OE="FALSE" USE_TERMINATION_CONTROL="FALSE" datain dataout
//VERSION_BEGIN 13.1 cbx_altiobuf_out 2013:10:17:04:07:49:SJ cbx_mgl 2013:10:17:04:34:36:SJ cbx_stratixiii 2013:10:17:04:07:49:SJ cbx_stratixv 2013:10:17:04:07:49:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = cycloneiii_io_obuf 128 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  Driver128b_iobuf_out_52t
	( 
	datain,
	dataout) ;
	input   [127:0]  datain;
	output   [127:0]  dataout;

	wire  [127:0]   wire_obufa_i;
	wire  [127:0]   wire_obufa_o;
	wire  [127:0]   wire_obufa_oe;
	wire  [127:0]  oe_w;

	cycloneiii_io_obuf   obufa_0
	( 
	.i(wire_obufa_i[0:0]),
	.o(wire_obufa_o[0:0]),
	.obar(),
	.oe(wire_obufa_oe[0:0])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_0.bus_hold = "false",
		obufa_0.open_drain_output = "false",
		obufa_0.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_1
	( 
	.i(wire_obufa_i[1:1]),
	.o(wire_obufa_o[1:1]),
	.obar(),
	.oe(wire_obufa_oe[1:1])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_1.bus_hold = "false",
		obufa_1.open_drain_output = "false",
		obufa_1.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_2
	( 
	.i(wire_obufa_i[2:2]),
	.o(wire_obufa_o[2:2]),
	.obar(),
	.oe(wire_obufa_oe[2:2])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_2.bus_hold = "false",
		obufa_2.open_drain_output = "false",
		obufa_2.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_3
	( 
	.i(wire_obufa_i[3:3]),
	.o(wire_obufa_o[3:3]),
	.obar(),
	.oe(wire_obufa_oe[3:3])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_3.bus_hold = "false",
		obufa_3.open_drain_output = "false",
		obufa_3.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_4
	( 
	.i(wire_obufa_i[4:4]),
	.o(wire_obufa_o[4:4]),
	.obar(),
	.oe(wire_obufa_oe[4:4])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_4.bus_hold = "false",
		obufa_4.open_drain_output = "false",
		obufa_4.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_5
	( 
	.i(wire_obufa_i[5:5]),
	.o(wire_obufa_o[5:5]),
	.obar(),
	.oe(wire_obufa_oe[5:5])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_5.bus_hold = "false",
		obufa_5.open_drain_output = "false",
		obufa_5.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_6
	( 
	.i(wire_obufa_i[6:6]),
	.o(wire_obufa_o[6:6]),
	.obar(),
	.oe(wire_obufa_oe[6:6])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_6.bus_hold = "false",
		obufa_6.open_drain_output = "false",
		obufa_6.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_7
	( 
	.i(wire_obufa_i[7:7]),
	.o(wire_obufa_o[7:7]),
	.obar(),
	.oe(wire_obufa_oe[7:7])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_7.bus_hold = "false",
		obufa_7.open_drain_output = "false",
		obufa_7.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_8
	( 
	.i(wire_obufa_i[8:8]),
	.o(wire_obufa_o[8:8]),
	.obar(),
	.oe(wire_obufa_oe[8:8])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_8.bus_hold = "false",
		obufa_8.open_drain_output = "false",
		obufa_8.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_9
	( 
	.i(wire_obufa_i[9:9]),
	.o(wire_obufa_o[9:9]),
	.obar(),
	.oe(wire_obufa_oe[9:9])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_9.bus_hold = "false",
		obufa_9.open_drain_output = "false",
		obufa_9.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_10
	( 
	.i(wire_obufa_i[10:10]),
	.o(wire_obufa_o[10:10]),
	.obar(),
	.oe(wire_obufa_oe[10:10])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_10.bus_hold = "false",
		obufa_10.open_drain_output = "false",
		obufa_10.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_11
	( 
	.i(wire_obufa_i[11:11]),
	.o(wire_obufa_o[11:11]),
	.obar(),
	.oe(wire_obufa_oe[11:11])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_11.bus_hold = "false",
		obufa_11.open_drain_output = "false",
		obufa_11.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_12
	( 
	.i(wire_obufa_i[12:12]),
	.o(wire_obufa_o[12:12]),
	.obar(),
	.oe(wire_obufa_oe[12:12])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_12.bus_hold = "false",
		obufa_12.open_drain_output = "false",
		obufa_12.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_13
	( 
	.i(wire_obufa_i[13:13]),
	.o(wire_obufa_o[13:13]),
	.obar(),
	.oe(wire_obufa_oe[13:13])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_13.bus_hold = "false",
		obufa_13.open_drain_output = "false",
		obufa_13.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_14
	( 
	.i(wire_obufa_i[14:14]),
	.o(wire_obufa_o[14:14]),
	.obar(),
	.oe(wire_obufa_oe[14:14])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_14.bus_hold = "false",
		obufa_14.open_drain_output = "false",
		obufa_14.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_15
	( 
	.i(wire_obufa_i[15:15]),
	.o(wire_obufa_o[15:15]),
	.obar(),
	.oe(wire_obufa_oe[15:15])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_15.bus_hold = "false",
		obufa_15.open_drain_output = "false",
		obufa_15.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_16
	( 
	.i(wire_obufa_i[16:16]),
	.o(wire_obufa_o[16:16]),
	.obar(),
	.oe(wire_obufa_oe[16:16])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_16.bus_hold = "false",
		obufa_16.open_drain_output = "false",
		obufa_16.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_17
	( 
	.i(wire_obufa_i[17:17]),
	.o(wire_obufa_o[17:17]),
	.obar(),
	.oe(wire_obufa_oe[17:17])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_17.bus_hold = "false",
		obufa_17.open_drain_output = "false",
		obufa_17.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_18
	( 
	.i(wire_obufa_i[18:18]),
	.o(wire_obufa_o[18:18]),
	.obar(),
	.oe(wire_obufa_oe[18:18])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_18.bus_hold = "false",
		obufa_18.open_drain_output = "false",
		obufa_18.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_19
	( 
	.i(wire_obufa_i[19:19]),
	.o(wire_obufa_o[19:19]),
	.obar(),
	.oe(wire_obufa_oe[19:19])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_19.bus_hold = "false",
		obufa_19.open_drain_output = "false",
		obufa_19.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_20
	( 
	.i(wire_obufa_i[20:20]),
	.o(wire_obufa_o[20:20]),
	.obar(),
	.oe(wire_obufa_oe[20:20])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_20.bus_hold = "false",
		obufa_20.open_drain_output = "false",
		obufa_20.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_21
	( 
	.i(wire_obufa_i[21:21]),
	.o(wire_obufa_o[21:21]),
	.obar(),
	.oe(wire_obufa_oe[21:21])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_21.bus_hold = "false",
		obufa_21.open_drain_output = "false",
		obufa_21.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_22
	( 
	.i(wire_obufa_i[22:22]),
	.o(wire_obufa_o[22:22]),
	.obar(),
	.oe(wire_obufa_oe[22:22])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_22.bus_hold = "false",
		obufa_22.open_drain_output = "false",
		obufa_22.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_23
	( 
	.i(wire_obufa_i[23:23]),
	.o(wire_obufa_o[23:23]),
	.obar(),
	.oe(wire_obufa_oe[23:23])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_23.bus_hold = "false",
		obufa_23.open_drain_output = "false",
		obufa_23.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_24
	( 
	.i(wire_obufa_i[24:24]),
	.o(wire_obufa_o[24:24]),
	.obar(),
	.oe(wire_obufa_oe[24:24])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_24.bus_hold = "false",
		obufa_24.open_drain_output = "false",
		obufa_24.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_25
	( 
	.i(wire_obufa_i[25:25]),
	.o(wire_obufa_o[25:25]),
	.obar(),
	.oe(wire_obufa_oe[25:25])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_25.bus_hold = "false",
		obufa_25.open_drain_output = "false",
		obufa_25.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_26
	( 
	.i(wire_obufa_i[26:26]),
	.o(wire_obufa_o[26:26]),
	.obar(),
	.oe(wire_obufa_oe[26:26])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_26.bus_hold = "false",
		obufa_26.open_drain_output = "false",
		obufa_26.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_27
	( 
	.i(wire_obufa_i[27:27]),
	.o(wire_obufa_o[27:27]),
	.obar(),
	.oe(wire_obufa_oe[27:27])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_27.bus_hold = "false",
		obufa_27.open_drain_output = "false",
		obufa_27.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_28
	( 
	.i(wire_obufa_i[28:28]),
	.o(wire_obufa_o[28:28]),
	.obar(),
	.oe(wire_obufa_oe[28:28])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_28.bus_hold = "false",
		obufa_28.open_drain_output = "false",
		obufa_28.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_29
	( 
	.i(wire_obufa_i[29:29]),
	.o(wire_obufa_o[29:29]),
	.obar(),
	.oe(wire_obufa_oe[29:29])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_29.bus_hold = "false",
		obufa_29.open_drain_output = "false",
		obufa_29.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_30
	( 
	.i(wire_obufa_i[30:30]),
	.o(wire_obufa_o[30:30]),
	.obar(),
	.oe(wire_obufa_oe[30:30])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_30.bus_hold = "false",
		obufa_30.open_drain_output = "false",
		obufa_30.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_31
	( 
	.i(wire_obufa_i[31:31]),
	.o(wire_obufa_o[31:31]),
	.obar(),
	.oe(wire_obufa_oe[31:31])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_31.bus_hold = "false",
		obufa_31.open_drain_output = "false",
		obufa_31.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_32
	( 
	.i(wire_obufa_i[32:32]),
	.o(wire_obufa_o[32:32]),
	.obar(),
	.oe(wire_obufa_oe[32:32])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_32.bus_hold = "false",
		obufa_32.open_drain_output = "false",
		obufa_32.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_33
	( 
	.i(wire_obufa_i[33:33]),
	.o(wire_obufa_o[33:33]),
	.obar(),
	.oe(wire_obufa_oe[33:33])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_33.bus_hold = "false",
		obufa_33.open_drain_output = "false",
		obufa_33.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_34
	( 
	.i(wire_obufa_i[34:34]),
	.o(wire_obufa_o[34:34]),
	.obar(),
	.oe(wire_obufa_oe[34:34])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_34.bus_hold = "false",
		obufa_34.open_drain_output = "false",
		obufa_34.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_35
	( 
	.i(wire_obufa_i[35:35]),
	.o(wire_obufa_o[35:35]),
	.obar(),
	.oe(wire_obufa_oe[35:35])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_35.bus_hold = "false",
		obufa_35.open_drain_output = "false",
		obufa_35.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_36
	( 
	.i(wire_obufa_i[36:36]),
	.o(wire_obufa_o[36:36]),
	.obar(),
	.oe(wire_obufa_oe[36:36])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_36.bus_hold = "false",
		obufa_36.open_drain_output = "false",
		obufa_36.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_37
	( 
	.i(wire_obufa_i[37:37]),
	.o(wire_obufa_o[37:37]),
	.obar(),
	.oe(wire_obufa_oe[37:37])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_37.bus_hold = "false",
		obufa_37.open_drain_output = "false",
		obufa_37.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_38
	( 
	.i(wire_obufa_i[38:38]),
	.o(wire_obufa_o[38:38]),
	.obar(),
	.oe(wire_obufa_oe[38:38])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_38.bus_hold = "false",
		obufa_38.open_drain_output = "false",
		obufa_38.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_39
	( 
	.i(wire_obufa_i[39:39]),
	.o(wire_obufa_o[39:39]),
	.obar(),
	.oe(wire_obufa_oe[39:39])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_39.bus_hold = "false",
		obufa_39.open_drain_output = "false",
		obufa_39.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_40
	( 
	.i(wire_obufa_i[40:40]),
	.o(wire_obufa_o[40:40]),
	.obar(),
	.oe(wire_obufa_oe[40:40])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_40.bus_hold = "false",
		obufa_40.open_drain_output = "false",
		obufa_40.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_41
	( 
	.i(wire_obufa_i[41:41]),
	.o(wire_obufa_o[41:41]),
	.obar(),
	.oe(wire_obufa_oe[41:41])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_41.bus_hold = "false",
		obufa_41.open_drain_output = "false",
		obufa_41.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_42
	( 
	.i(wire_obufa_i[42:42]),
	.o(wire_obufa_o[42:42]),
	.obar(),
	.oe(wire_obufa_oe[42:42])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_42.bus_hold = "false",
		obufa_42.open_drain_output = "false",
		obufa_42.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_43
	( 
	.i(wire_obufa_i[43:43]),
	.o(wire_obufa_o[43:43]),
	.obar(),
	.oe(wire_obufa_oe[43:43])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_43.bus_hold = "false",
		obufa_43.open_drain_output = "false",
		obufa_43.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_44
	( 
	.i(wire_obufa_i[44:44]),
	.o(wire_obufa_o[44:44]),
	.obar(),
	.oe(wire_obufa_oe[44:44])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_44.bus_hold = "false",
		obufa_44.open_drain_output = "false",
		obufa_44.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_45
	( 
	.i(wire_obufa_i[45:45]),
	.o(wire_obufa_o[45:45]),
	.obar(),
	.oe(wire_obufa_oe[45:45])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_45.bus_hold = "false",
		obufa_45.open_drain_output = "false",
		obufa_45.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_46
	( 
	.i(wire_obufa_i[46:46]),
	.o(wire_obufa_o[46:46]),
	.obar(),
	.oe(wire_obufa_oe[46:46])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_46.bus_hold = "false",
		obufa_46.open_drain_output = "false",
		obufa_46.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_47
	( 
	.i(wire_obufa_i[47:47]),
	.o(wire_obufa_o[47:47]),
	.obar(),
	.oe(wire_obufa_oe[47:47])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_47.bus_hold = "false",
		obufa_47.open_drain_output = "false",
		obufa_47.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_48
	( 
	.i(wire_obufa_i[48:48]),
	.o(wire_obufa_o[48:48]),
	.obar(),
	.oe(wire_obufa_oe[48:48])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_48.bus_hold = "false",
		obufa_48.open_drain_output = "false",
		obufa_48.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_49
	( 
	.i(wire_obufa_i[49:49]),
	.o(wire_obufa_o[49:49]),
	.obar(),
	.oe(wire_obufa_oe[49:49])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_49.bus_hold = "false",
		obufa_49.open_drain_output = "false",
		obufa_49.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_50
	( 
	.i(wire_obufa_i[50:50]),
	.o(wire_obufa_o[50:50]),
	.obar(),
	.oe(wire_obufa_oe[50:50])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_50.bus_hold = "false",
		obufa_50.open_drain_output = "false",
		obufa_50.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_51
	( 
	.i(wire_obufa_i[51:51]),
	.o(wire_obufa_o[51:51]),
	.obar(),
	.oe(wire_obufa_oe[51:51])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_51.bus_hold = "false",
		obufa_51.open_drain_output = "false",
		obufa_51.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_52
	( 
	.i(wire_obufa_i[52:52]),
	.o(wire_obufa_o[52:52]),
	.obar(),
	.oe(wire_obufa_oe[52:52])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_52.bus_hold = "false",
		obufa_52.open_drain_output = "false",
		obufa_52.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_53
	( 
	.i(wire_obufa_i[53:53]),
	.o(wire_obufa_o[53:53]),
	.obar(),
	.oe(wire_obufa_oe[53:53])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_53.bus_hold = "false",
		obufa_53.open_drain_output = "false",
		obufa_53.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_54
	( 
	.i(wire_obufa_i[54:54]),
	.o(wire_obufa_o[54:54]),
	.obar(),
	.oe(wire_obufa_oe[54:54])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_54.bus_hold = "false",
		obufa_54.open_drain_output = "false",
		obufa_54.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_55
	( 
	.i(wire_obufa_i[55:55]),
	.o(wire_obufa_o[55:55]),
	.obar(),
	.oe(wire_obufa_oe[55:55])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_55.bus_hold = "false",
		obufa_55.open_drain_output = "false",
		obufa_55.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_56
	( 
	.i(wire_obufa_i[56:56]),
	.o(wire_obufa_o[56:56]),
	.obar(),
	.oe(wire_obufa_oe[56:56])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_56.bus_hold = "false",
		obufa_56.open_drain_output = "false",
		obufa_56.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_57
	( 
	.i(wire_obufa_i[57:57]),
	.o(wire_obufa_o[57:57]),
	.obar(),
	.oe(wire_obufa_oe[57:57])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_57.bus_hold = "false",
		obufa_57.open_drain_output = "false",
		obufa_57.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_58
	( 
	.i(wire_obufa_i[58:58]),
	.o(wire_obufa_o[58:58]),
	.obar(),
	.oe(wire_obufa_oe[58:58])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_58.bus_hold = "false",
		obufa_58.open_drain_output = "false",
		obufa_58.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_59
	( 
	.i(wire_obufa_i[59:59]),
	.o(wire_obufa_o[59:59]),
	.obar(),
	.oe(wire_obufa_oe[59:59])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_59.bus_hold = "false",
		obufa_59.open_drain_output = "false",
		obufa_59.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_60
	( 
	.i(wire_obufa_i[60:60]),
	.o(wire_obufa_o[60:60]),
	.obar(),
	.oe(wire_obufa_oe[60:60])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_60.bus_hold = "false",
		obufa_60.open_drain_output = "false",
		obufa_60.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_61
	( 
	.i(wire_obufa_i[61:61]),
	.o(wire_obufa_o[61:61]),
	.obar(),
	.oe(wire_obufa_oe[61:61])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_61.bus_hold = "false",
		obufa_61.open_drain_output = "false",
		obufa_61.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_62
	( 
	.i(wire_obufa_i[62:62]),
	.o(wire_obufa_o[62:62]),
	.obar(),
	.oe(wire_obufa_oe[62:62])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_62.bus_hold = "false",
		obufa_62.open_drain_output = "false",
		obufa_62.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_63
	( 
	.i(wire_obufa_i[63:63]),
	.o(wire_obufa_o[63:63]),
	.obar(),
	.oe(wire_obufa_oe[63:63])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_63.bus_hold = "false",
		obufa_63.open_drain_output = "false",
		obufa_63.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_64
	( 
	.i(wire_obufa_i[64:64]),
	.o(wire_obufa_o[64:64]),
	.obar(),
	.oe(wire_obufa_oe[64:64])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_64.bus_hold = "false",
		obufa_64.open_drain_output = "false",
		obufa_64.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_65
	( 
	.i(wire_obufa_i[65:65]),
	.o(wire_obufa_o[65:65]),
	.obar(),
	.oe(wire_obufa_oe[65:65])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_65.bus_hold = "false",
		obufa_65.open_drain_output = "false",
		obufa_65.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_66
	( 
	.i(wire_obufa_i[66:66]),
	.o(wire_obufa_o[66:66]),
	.obar(),
	.oe(wire_obufa_oe[66:66])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_66.bus_hold = "false",
		obufa_66.open_drain_output = "false",
		obufa_66.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_67
	( 
	.i(wire_obufa_i[67:67]),
	.o(wire_obufa_o[67:67]),
	.obar(),
	.oe(wire_obufa_oe[67:67])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_67.bus_hold = "false",
		obufa_67.open_drain_output = "false",
		obufa_67.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_68
	( 
	.i(wire_obufa_i[68:68]),
	.o(wire_obufa_o[68:68]),
	.obar(),
	.oe(wire_obufa_oe[68:68])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_68.bus_hold = "false",
		obufa_68.open_drain_output = "false",
		obufa_68.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_69
	( 
	.i(wire_obufa_i[69:69]),
	.o(wire_obufa_o[69:69]),
	.obar(),
	.oe(wire_obufa_oe[69:69])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_69.bus_hold = "false",
		obufa_69.open_drain_output = "false",
		obufa_69.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_70
	( 
	.i(wire_obufa_i[70:70]),
	.o(wire_obufa_o[70:70]),
	.obar(),
	.oe(wire_obufa_oe[70:70])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_70.bus_hold = "false",
		obufa_70.open_drain_output = "false",
		obufa_70.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_71
	( 
	.i(wire_obufa_i[71:71]),
	.o(wire_obufa_o[71:71]),
	.obar(),
	.oe(wire_obufa_oe[71:71])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_71.bus_hold = "false",
		obufa_71.open_drain_output = "false",
		obufa_71.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_72
	( 
	.i(wire_obufa_i[72:72]),
	.o(wire_obufa_o[72:72]),
	.obar(),
	.oe(wire_obufa_oe[72:72])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_72.bus_hold = "false",
		obufa_72.open_drain_output = "false",
		obufa_72.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_73
	( 
	.i(wire_obufa_i[73:73]),
	.o(wire_obufa_o[73:73]),
	.obar(),
	.oe(wire_obufa_oe[73:73])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_73.bus_hold = "false",
		obufa_73.open_drain_output = "false",
		obufa_73.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_74
	( 
	.i(wire_obufa_i[74:74]),
	.o(wire_obufa_o[74:74]),
	.obar(),
	.oe(wire_obufa_oe[74:74])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_74.bus_hold = "false",
		obufa_74.open_drain_output = "false",
		obufa_74.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_75
	( 
	.i(wire_obufa_i[75:75]),
	.o(wire_obufa_o[75:75]),
	.obar(),
	.oe(wire_obufa_oe[75:75])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_75.bus_hold = "false",
		obufa_75.open_drain_output = "false",
		obufa_75.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_76
	( 
	.i(wire_obufa_i[76:76]),
	.o(wire_obufa_o[76:76]),
	.obar(),
	.oe(wire_obufa_oe[76:76])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_76.bus_hold = "false",
		obufa_76.open_drain_output = "false",
		obufa_76.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_77
	( 
	.i(wire_obufa_i[77:77]),
	.o(wire_obufa_o[77:77]),
	.obar(),
	.oe(wire_obufa_oe[77:77])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_77.bus_hold = "false",
		obufa_77.open_drain_output = "false",
		obufa_77.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_78
	( 
	.i(wire_obufa_i[78:78]),
	.o(wire_obufa_o[78:78]),
	.obar(),
	.oe(wire_obufa_oe[78:78])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_78.bus_hold = "false",
		obufa_78.open_drain_output = "false",
		obufa_78.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_79
	( 
	.i(wire_obufa_i[79:79]),
	.o(wire_obufa_o[79:79]),
	.obar(),
	.oe(wire_obufa_oe[79:79])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_79.bus_hold = "false",
		obufa_79.open_drain_output = "false",
		obufa_79.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_80
	( 
	.i(wire_obufa_i[80:80]),
	.o(wire_obufa_o[80:80]),
	.obar(),
	.oe(wire_obufa_oe[80:80])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_80.bus_hold = "false",
		obufa_80.open_drain_output = "false",
		obufa_80.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_81
	( 
	.i(wire_obufa_i[81:81]),
	.o(wire_obufa_o[81:81]),
	.obar(),
	.oe(wire_obufa_oe[81:81])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_81.bus_hold = "false",
		obufa_81.open_drain_output = "false",
		obufa_81.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_82
	( 
	.i(wire_obufa_i[82:82]),
	.o(wire_obufa_o[82:82]),
	.obar(),
	.oe(wire_obufa_oe[82:82])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_82.bus_hold = "false",
		obufa_82.open_drain_output = "false",
		obufa_82.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_83
	( 
	.i(wire_obufa_i[83:83]),
	.o(wire_obufa_o[83:83]),
	.obar(),
	.oe(wire_obufa_oe[83:83])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_83.bus_hold = "false",
		obufa_83.open_drain_output = "false",
		obufa_83.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_84
	( 
	.i(wire_obufa_i[84:84]),
	.o(wire_obufa_o[84:84]),
	.obar(),
	.oe(wire_obufa_oe[84:84])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_84.bus_hold = "false",
		obufa_84.open_drain_output = "false",
		obufa_84.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_85
	( 
	.i(wire_obufa_i[85:85]),
	.o(wire_obufa_o[85:85]),
	.obar(),
	.oe(wire_obufa_oe[85:85])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_85.bus_hold = "false",
		obufa_85.open_drain_output = "false",
		obufa_85.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_86
	( 
	.i(wire_obufa_i[86:86]),
	.o(wire_obufa_o[86:86]),
	.obar(),
	.oe(wire_obufa_oe[86:86])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_86.bus_hold = "false",
		obufa_86.open_drain_output = "false",
		obufa_86.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_87
	( 
	.i(wire_obufa_i[87:87]),
	.o(wire_obufa_o[87:87]),
	.obar(),
	.oe(wire_obufa_oe[87:87])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_87.bus_hold = "false",
		obufa_87.open_drain_output = "false",
		obufa_87.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_88
	( 
	.i(wire_obufa_i[88:88]),
	.o(wire_obufa_o[88:88]),
	.obar(),
	.oe(wire_obufa_oe[88:88])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_88.bus_hold = "false",
		obufa_88.open_drain_output = "false",
		obufa_88.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_89
	( 
	.i(wire_obufa_i[89:89]),
	.o(wire_obufa_o[89:89]),
	.obar(),
	.oe(wire_obufa_oe[89:89])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_89.bus_hold = "false",
		obufa_89.open_drain_output = "false",
		obufa_89.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_90
	( 
	.i(wire_obufa_i[90:90]),
	.o(wire_obufa_o[90:90]),
	.obar(),
	.oe(wire_obufa_oe[90:90])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_90.bus_hold = "false",
		obufa_90.open_drain_output = "false",
		obufa_90.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_91
	( 
	.i(wire_obufa_i[91:91]),
	.o(wire_obufa_o[91:91]),
	.obar(),
	.oe(wire_obufa_oe[91:91])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_91.bus_hold = "false",
		obufa_91.open_drain_output = "false",
		obufa_91.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_92
	( 
	.i(wire_obufa_i[92:92]),
	.o(wire_obufa_o[92:92]),
	.obar(),
	.oe(wire_obufa_oe[92:92])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_92.bus_hold = "false",
		obufa_92.open_drain_output = "false",
		obufa_92.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_93
	( 
	.i(wire_obufa_i[93:93]),
	.o(wire_obufa_o[93:93]),
	.obar(),
	.oe(wire_obufa_oe[93:93])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_93.bus_hold = "false",
		obufa_93.open_drain_output = "false",
		obufa_93.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_94
	( 
	.i(wire_obufa_i[94:94]),
	.o(wire_obufa_o[94:94]),
	.obar(),
	.oe(wire_obufa_oe[94:94])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_94.bus_hold = "false",
		obufa_94.open_drain_output = "false",
		obufa_94.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_95
	( 
	.i(wire_obufa_i[95:95]),
	.o(wire_obufa_o[95:95]),
	.obar(),
	.oe(wire_obufa_oe[95:95])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_95.bus_hold = "false",
		obufa_95.open_drain_output = "false",
		obufa_95.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_96
	( 
	.i(wire_obufa_i[96:96]),
	.o(wire_obufa_o[96:96]),
	.obar(),
	.oe(wire_obufa_oe[96:96])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_96.bus_hold = "false",
		obufa_96.open_drain_output = "false",
		obufa_96.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_97
	( 
	.i(wire_obufa_i[97:97]),
	.o(wire_obufa_o[97:97]),
	.obar(),
	.oe(wire_obufa_oe[97:97])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_97.bus_hold = "false",
		obufa_97.open_drain_output = "false",
		obufa_97.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_98
	( 
	.i(wire_obufa_i[98:98]),
	.o(wire_obufa_o[98:98]),
	.obar(),
	.oe(wire_obufa_oe[98:98])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_98.bus_hold = "false",
		obufa_98.open_drain_output = "false",
		obufa_98.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_99
	( 
	.i(wire_obufa_i[99:99]),
	.o(wire_obufa_o[99:99]),
	.obar(),
	.oe(wire_obufa_oe[99:99])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_99.bus_hold = "false",
		obufa_99.open_drain_output = "false",
		obufa_99.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_100
	( 
	.i(wire_obufa_i[100:100]),
	.o(wire_obufa_o[100:100]),
	.obar(),
	.oe(wire_obufa_oe[100:100])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_100.bus_hold = "false",
		obufa_100.open_drain_output = "false",
		obufa_100.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_101
	( 
	.i(wire_obufa_i[101:101]),
	.o(wire_obufa_o[101:101]),
	.obar(),
	.oe(wire_obufa_oe[101:101])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_101.bus_hold = "false",
		obufa_101.open_drain_output = "false",
		obufa_101.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_102
	( 
	.i(wire_obufa_i[102:102]),
	.o(wire_obufa_o[102:102]),
	.obar(),
	.oe(wire_obufa_oe[102:102])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_102.bus_hold = "false",
		obufa_102.open_drain_output = "false",
		obufa_102.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_103
	( 
	.i(wire_obufa_i[103:103]),
	.o(wire_obufa_o[103:103]),
	.obar(),
	.oe(wire_obufa_oe[103:103])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_103.bus_hold = "false",
		obufa_103.open_drain_output = "false",
		obufa_103.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_104
	( 
	.i(wire_obufa_i[104:104]),
	.o(wire_obufa_o[104:104]),
	.obar(),
	.oe(wire_obufa_oe[104:104])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_104.bus_hold = "false",
		obufa_104.open_drain_output = "false",
		obufa_104.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_105
	( 
	.i(wire_obufa_i[105:105]),
	.o(wire_obufa_o[105:105]),
	.obar(),
	.oe(wire_obufa_oe[105:105])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_105.bus_hold = "false",
		obufa_105.open_drain_output = "false",
		obufa_105.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_106
	( 
	.i(wire_obufa_i[106:106]),
	.o(wire_obufa_o[106:106]),
	.obar(),
	.oe(wire_obufa_oe[106:106])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_106.bus_hold = "false",
		obufa_106.open_drain_output = "false",
		obufa_106.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_107
	( 
	.i(wire_obufa_i[107:107]),
	.o(wire_obufa_o[107:107]),
	.obar(),
	.oe(wire_obufa_oe[107:107])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_107.bus_hold = "false",
		obufa_107.open_drain_output = "false",
		obufa_107.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_108
	( 
	.i(wire_obufa_i[108:108]),
	.o(wire_obufa_o[108:108]),
	.obar(),
	.oe(wire_obufa_oe[108:108])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_108.bus_hold = "false",
		obufa_108.open_drain_output = "false",
		obufa_108.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_109
	( 
	.i(wire_obufa_i[109:109]),
	.o(wire_obufa_o[109:109]),
	.obar(),
	.oe(wire_obufa_oe[109:109])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_109.bus_hold = "false",
		obufa_109.open_drain_output = "false",
		obufa_109.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_110
	( 
	.i(wire_obufa_i[110:110]),
	.o(wire_obufa_o[110:110]),
	.obar(),
	.oe(wire_obufa_oe[110:110])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_110.bus_hold = "false",
		obufa_110.open_drain_output = "false",
		obufa_110.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_111
	( 
	.i(wire_obufa_i[111:111]),
	.o(wire_obufa_o[111:111]),
	.obar(),
	.oe(wire_obufa_oe[111:111])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_111.bus_hold = "false",
		obufa_111.open_drain_output = "false",
		obufa_111.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_112
	( 
	.i(wire_obufa_i[112:112]),
	.o(wire_obufa_o[112:112]),
	.obar(),
	.oe(wire_obufa_oe[112:112])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_112.bus_hold = "false",
		obufa_112.open_drain_output = "false",
		obufa_112.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_113
	( 
	.i(wire_obufa_i[113:113]),
	.o(wire_obufa_o[113:113]),
	.obar(),
	.oe(wire_obufa_oe[113:113])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_113.bus_hold = "false",
		obufa_113.open_drain_output = "false",
		obufa_113.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_114
	( 
	.i(wire_obufa_i[114:114]),
	.o(wire_obufa_o[114:114]),
	.obar(),
	.oe(wire_obufa_oe[114:114])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_114.bus_hold = "false",
		obufa_114.open_drain_output = "false",
		obufa_114.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_115
	( 
	.i(wire_obufa_i[115:115]),
	.o(wire_obufa_o[115:115]),
	.obar(),
	.oe(wire_obufa_oe[115:115])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_115.bus_hold = "false",
		obufa_115.open_drain_output = "false",
		obufa_115.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_116
	( 
	.i(wire_obufa_i[116:116]),
	.o(wire_obufa_o[116:116]),
	.obar(),
	.oe(wire_obufa_oe[116:116])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_116.bus_hold = "false",
		obufa_116.open_drain_output = "false",
		obufa_116.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_117
	( 
	.i(wire_obufa_i[117:117]),
	.o(wire_obufa_o[117:117]),
	.obar(),
	.oe(wire_obufa_oe[117:117])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_117.bus_hold = "false",
		obufa_117.open_drain_output = "false",
		obufa_117.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_118
	( 
	.i(wire_obufa_i[118:118]),
	.o(wire_obufa_o[118:118]),
	.obar(),
	.oe(wire_obufa_oe[118:118])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_118.bus_hold = "false",
		obufa_118.open_drain_output = "false",
		obufa_118.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_119
	( 
	.i(wire_obufa_i[119:119]),
	.o(wire_obufa_o[119:119]),
	.obar(),
	.oe(wire_obufa_oe[119:119])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_119.bus_hold = "false",
		obufa_119.open_drain_output = "false",
		obufa_119.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_120
	( 
	.i(wire_obufa_i[120:120]),
	.o(wire_obufa_o[120:120]),
	.obar(),
	.oe(wire_obufa_oe[120:120])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_120.bus_hold = "false",
		obufa_120.open_drain_output = "false",
		obufa_120.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_121
	( 
	.i(wire_obufa_i[121:121]),
	.o(wire_obufa_o[121:121]),
	.obar(),
	.oe(wire_obufa_oe[121:121])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_121.bus_hold = "false",
		obufa_121.open_drain_output = "false",
		obufa_121.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_122
	( 
	.i(wire_obufa_i[122:122]),
	.o(wire_obufa_o[122:122]),
	.obar(),
	.oe(wire_obufa_oe[122:122])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_122.bus_hold = "false",
		obufa_122.open_drain_output = "false",
		obufa_122.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_123
	( 
	.i(wire_obufa_i[123:123]),
	.o(wire_obufa_o[123:123]),
	.obar(),
	.oe(wire_obufa_oe[123:123])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_123.bus_hold = "false",
		obufa_123.open_drain_output = "false",
		obufa_123.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_124
	( 
	.i(wire_obufa_i[124:124]),
	.o(wire_obufa_o[124:124]),
	.obar(),
	.oe(wire_obufa_oe[124:124])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_124.bus_hold = "false",
		obufa_124.open_drain_output = "false",
		obufa_124.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_125
	( 
	.i(wire_obufa_i[125:125]),
	.o(wire_obufa_o[125:125]),
	.obar(),
	.oe(wire_obufa_oe[125:125])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_125.bus_hold = "false",
		obufa_125.open_drain_output = "false",
		obufa_125.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_126
	( 
	.i(wire_obufa_i[126:126]),
	.o(wire_obufa_o[126:126]),
	.obar(),
	.oe(wire_obufa_oe[126:126])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_126.bus_hold = "false",
		obufa_126.open_drain_output = "false",
		obufa_126.lpm_type = "cycloneiii_io_obuf";
	cycloneiii_io_obuf   obufa_127
	( 
	.i(wire_obufa_i[127:127]),
	.o(wire_obufa_o[127:127]),
	.obar(),
	.oe(wire_obufa_oe[127:127])
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.seriesterminationcontrol({16{1'b0}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devoe(1'b1)
	// synopsys translate_on
	);
	defparam
		obufa_127.bus_hold = "false",
		obufa_127.open_drain_output = "false",
		obufa_127.lpm_type = "cycloneiii_io_obuf";
	assign
		wire_obufa_i = datain,
		wire_obufa_oe = oe_w;
	assign
		dataout = wire_obufa_o,
		oe_w = {128{1'b1}};
endmodule //Driver128b_iobuf_out_52t
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module Driver128b (
	datain,
	dataout);

	input	[127:0]  datain;
	output	[127:0]  dataout;

	wire [127:0] sub_wire0;
	wire [127:0] dataout = sub_wire0[127:0];

	Driver128b_iobuf_out_52t	Driver128b_iobuf_out_52t_component (
				.datain (datain),
				.dataout (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone III"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone III"
// Retrieval info: CONSTANT: enable_bus_hold STRING "FALSE"
// Retrieval info: CONSTANT: left_shift_series_termination_control STRING "FALSE"
// Retrieval info: CONSTANT: number_of_channels NUMERIC "128"
// Retrieval info: CONSTANT: open_drain_output STRING "FALSE"
// Retrieval info: CONSTANT: pseudo_differential_mode STRING "FALSE"
// Retrieval info: CONSTANT: use_differential_mode STRING "FALSE"
// Retrieval info: CONSTANT: use_oe STRING "FALSE"
// Retrieval info: CONSTANT: use_termination_control STRING "FALSE"
// Retrieval info: USED_PORT: datain 0 0 128 0 INPUT NODEFVAL "datain[127..0]"
// Retrieval info: USED_PORT: dataout 0 0 128 0 OUTPUT NODEFVAL "dataout[127..0]"
// Retrieval info: CONNECT: @datain 0 0 128 0 datain 0 0 128 0
// Retrieval info: CONNECT: dataout 0 0 128 0 @dataout 0 0 128 0
// Retrieval info: GEN_FILE: TYPE_NORMAL Driver128b.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Driver128b.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Driver128b.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Driver128b.bsf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL Driver128b_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL Driver128b_bb.v TRUE
// Retrieval info: LIB_FILE: cycloneiii
