#!/usr/bin/env tclsh
set FIRMWARE_ID 0xafd0
set gitversion [ exec git describe --tags ]
regexp {v([0-9]*).([0-9]*)(-[0-9]*-g([0-9a-z]*))?} $gitversion matched major minor verincr thash
set githashfull [ exec git rev-parse --verify HEAD ]
regexp {([0-9a-z]{8})} $githashfull hash
set version [ format H"%x" [ expr ($FIRMWARE_ID << 16) | ($major<<8) | $minor ] ]

set id [ format H"%x" $FIRMWARE_ID ]
set hash [ format H"%x" 0x$hash ]

set filename version.tdf
set file [open $filename w]
puts $file "-- version information for gx3500-timing-generator package"
puts $file "-- Note:  This file is automatically generated from version.tcl"
puts $file ""
puts $file "TITLE \"GX3500 Timing Generator Version\";"
puts $file ""
puts $file "SUBDESIGN version"
puts $file "("
puts $file "  id\[15..0]   : output;"
puts $file "  major\[7..0] : output;"
puts $file "  minor\[7..0] : output;"
puts $file "  value\[31..0] : output;"
puts $file "  hash\[31..0]  : output;"
puts $file ")"
puts $file ""
puts $file "BEGIN"
puts $file "  id\[]     = $id;"
puts $file "  major\[]  = $major;"
puts $file "  major\[]  = $minor;"
puts $file "  value\[]  = $version;"
puts $file "  hash\[]   = $hash;"
puts $file "END;"

close $file
